-- Usuarios da plataforma (senha apenas como hash BCrypt) com registro do aceite da LGPD.
CREATE TABLE app_user (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100) NOT NULL,
    email             VARCHAR(150) NOT NULL UNIQUE,
    password_hash     VARCHAR(100) NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    terms_accepted_at TIMESTAMP(6) NOT NULL,
    terms_version     VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_app_user_role CHECK (role IN ('STUDENT', 'ADMIN'))
);
