-- Log de auditoria das acoes dos usuarios. Sem FK para app_user: o registro precisa
-- sobreviver a exclusao da conta (rastreabilidade / Marco Civil da Internet, art. 15).
CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user_id    BIGINT,
    user_email VARCHAR(150),
    action     VARCHAR(40)  NOT NULL,
    resource   VARCHAR(200),
    details    VARCHAR(500),
    ip_address VARCHAR(45),
    success    BOOLEAN      NOT NULL
);
CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);
CREATE INDEX idx_audit_log_action ON audit_log (action);
